import Link from "next/link";
import { ArrowRight, Check, Heart, Music2, Sparkles } from "lucide-react";
import { ContextualCreateSongCTA } from "@/components/content/ContextualCreateSongCTA";
import { InlineDemoPlayer } from "@/components/content/InlineDemoPlayer";

type Props = { kind: "anniversary" | "wedding" };

const copy = {
  anniversary: { eyebrow: "Anniversary songs", title: "A custom anniversary song for the life you built together.", description: "Turn the small memories, private jokes, and years you chose each other into an original song they can replay long after the celebration.", genre: "acoustic", demo: "The Years Between Us", demoDescription: "Romantic acoustic · a Songtell demo", prompts: ["The place you first met", "A routine that became yours", "What you still choose every day"] },
  wedding: { eyebrow: "Wedding songs", title: "Write the wedding song no one else could have written.", description: "From first dance to final send-off, Songtell turns your shared story into an original track with lyrics, melody, and a moment worth replaying.", genre: "edm", demo: "Neon Vows", demoDescription: "Melodic EDM · a Songtell demo", prompts: ["How your story started", "The promise you want to make", "The room you want to move"] },
} as const;

export default function SongtellOccasionPage({ kind }: Props) {
  const data = copy[kind];
  return <main className="public-creem-page w-full"><section className="px-5 py-32 sm:px-8 lg:px-12 lg:py-40"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1fr_.75fr] lg:items-center"><div><p className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[.16em]"><Sparkles className="size-3.5" /> {data.eyebrow}</p><h1 className="mt-5 max-w-3xl font-display text-5xl leading-[1.02] sm:text-6xl">{data.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 opacity-75">{data.description}</p><Link href={`/create-song?occasion=${kind}&genre=${data.genre}`} className="creem-action-button mt-8 inline-flex items-center gap-2 px-5 py-3.5 text-sm font-bold">Start with your story <ArrowRight className="size-4" /></Link></div><div className="p-6"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-[.12em]"><span>Songtell original</span><Music2 className="size-4" /></div><h2 className="mt-14 text-4xl">{data.demo}</h2><InlineDemoPlayer title={data.demo} subtitle={data.demoDescription} /></div></div></section><section className="px-5 py-20 sm:px-8 lg:px-12"><div className="mx-auto max-w-7xl"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em]">Start with a detail</p><h2 className="mt-3 text-4xl">The best songs sound like a real person.</h2><p className="mt-4 leading-7 opacity-75">You do not need perfect lyrics. Give us a few true details and we will help shape them into a song with a point of view.</p></div><div className="grid gap-4 sm:grid-cols-3">{data.prompts.map((prompt) => <div key={prompt} className="border-t-[3px] border-[var(--songtell-ink)] pt-4"><Heart className="size-4" /><p className="mt-4 font-semibold leading-6">{prompt}</p></div>)}</div></div><div className="mt-16 grid gap-4 md:grid-cols-3">{[["Choose the moment", "Anniversary, first dance, vows, or a private surprise."], ["Choose the sound", "Acoustic, EDM, ballad, indie, and more."], ["Choose what to keep", "A playable page, dynamic lyrics, and a video to share."]].map(([title, description]) => <div key={title} className="p-5"><Check className="size-5" /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 opacity-75">{description}</p></div>)}</div><ContextualCreateSongCTA occasion={kind} genre={data.genre} /></div></section></main>;
}
