import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { Locale } from "@/i18n/routing";
import { constructMetadata } from "@/lib/metadata";
import { Metadata } from "next";

type Params = Promise<{ locale: string }>;
export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> { const { locale } = await params; return constructMetadata({ title: "Songfinch Alternative for Personal Songs | Songtell", description: "Compare the Songtell creation flow with traditional custom song platforms by preview, editing, delivery, and digital keepsakes.", locale: locale as Locale, path: "/compare/songfinch-alternative", availableLocales: ["en"] }); }
export default function SongfinchAlternativePage() { return <main className="public-creem-page w-full"><section className="px-5 py-32 sm:px-8 lg:px-12 lg:py-40"><div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[.16em]">A considered alternative</p><h1 className="mt-5 max-w-3xl font-display text-5xl leading-tight tracking-[.02em] sm:text-6xl">Looking for a Songfinch alternative? Start with the story.</h1><p className="mt-6 max-w-2xl text-lg leading-8 opacity-75">Songtell is built for people who want to preview an original song quickly, shape the feeling, and share a finished digital keepsake.</p></div></section><section className="px-5 py-16 sm:px-8 lg:px-12"><div className="mx-auto max-w-5xl"><div className="overflow-x-auto"><table className="w-full min-w-[640px] border-collapse text-left text-sm"><thead><tr><th className="p-4 font-bold">What to compare</th><th className="p-4 font-bold">Songtell</th><th className="p-4 font-bold">Traditional custom song service</th></tr></thead><tbody>{[["Preview", "Preview the direction before unlocking", "Often begins after an order or brief"], ["Creative control", "Edit lyrics and choose a genre in the flow", "Depends on the service and revision policy"], ["Delivery", "Playable page, lyrics, and optional video", "Usually a finished audio file"], ["Best for", "Fast, personal digital gifts", "A managed production experience"]].map(([label, songtell, other]) => <tr key={label}><th className="p-4 font-semibold">{label}</th><td className="p-4"><Check className="mr-2 inline size-4" />{songtell}</td><td className="p-4 opacity-70">{other}</td></tr>)}</tbody></table></div><p className="mt-5 text-xs leading-6 opacity-60">Features and pricing change over time. Check each provider’s current offer before purchasing; this page describes Songtell’s workflow and does not make claims about another company’s current terms.</p><div className="public-creem-dark mt-12 flex flex-col justify-between gap-5 p-7 sm:flex-row sm:items-center"><div><h2 className="font-display text-3xl">Make the comparison personal.</h2><p className="mt-2 opacity-75">Bring a real memory and preview the first version.</p></div><Link href="/create-song" className="creem-action-button inline-flex items-center justify-center gap-2 px-5 py-3 text-sm font-bold">Create your song <ArrowRight className="size-4" /></Link></div></div></section></main>; }
